export const GET_COMPLETED_BOOKINGS_REQUEST = 'GET_COMPLETED_BOOKINGS_REQUEST';
export const GET_COMPLETED_BOOKINGS_SUCCESS = 'GET_COMPLETED_BOOKINGS_SUCCESS';
export const GET_COMPLETED_BOOKINGS_FAIL = 'GET_COMPLETED_BOOKINGS_FAIL';

export const GET_FUTURE_BOOKINGS_REQUEST = 'GET_FUTURE_BOOKINGS_REQUEST';
export const GET_FUTURE_BOOKINGS_SUCCESS = 'GET_FUTURE_BOOKINGS_SUCCESS';
export const GET_FUTURE_BOOKINGS_FAIL = 'GET_FUTURE_BOOKINGS_FAIL';

export const GET_CURRENT_BOOKINGS_REQUEST = 'GET_CURRENT_BOOKINGS_REQUEST';
export const GET_CURRENT_BOOKINGS_SUCCESS = 'GET_CURRENT_BOOKINGS_SUCCESS';
export const GET_CURRENT_BOOKINGS_FAIL = 'GET_CURRENT_BOOKINGS_FAIL';

export const UPDATE_BOOKING_STATUS_REQUEST = 'UPDATE_BOOKING_STATUS_REQUEST';
export const UPDATE_BOOKING_STATUS_SUCCESS = 'UPDATE_BOOKING_STATUS_SUCCESS';
export const UPDATE_BOOKING_STATUS_FAIL = 'UPDATE_BOOKING_STATUS_FAIL';

export const GET_PENDING_AMOUNT_REQUEST = 'GET_PENDING_AMOUNT_REQUEST';
export const GET_PENDING_AMOUNT_SUCCESS = 'GET_PENDING_AMOUNT_SUCCESS';
export const GET_PENDING_AMOUNT_FAIL = 'GET_PENDING_AMOUNT_FAIL';

export const CANCEL_BOOKING_REQUEST = 'CANCEL_BOOKING_REQUEST';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAIL = 'CANCEL_BOOKING_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
