export const REDEEM_REQUEST = "REDEEM_REQUEST"
export const REDEEM_SUCCESS = "REDEEM_SUCCESS"
export const REDEEM_FAIL = "REDEEM_FAIL"

export const REDEEM_DETAILS_REQUEST = "REDEEM_DETAILS_REQUEST"
export const REDEEM_DETAILS_SUCCESS = "REDEEM_DETAILS_SUCCESS"
export const REDEEM_DETAILS_FAIL = "REDEEM_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"