export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const LOGIN_VERIFY_REQUEST = "LOGIN_VERIFY_REQUEST"
export const LOGIN_VERIFY_SUCCESS = "LOGIN_VERIFY_SUCCESS"
export const LOGIN_VERIFY_FAIL = "LOGIN_VERIFY_FAIL"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const REGISTER_VERIFY_REQUEST = "REGISTER_VERIFY_REQUEST"
export const REGISTER_VERIFY_SUCCESS = "REGISTER_VERIFY_SUCCESS"
export const REGISTER_VERIFY_FAIL = "REGISTER_VERIFY_FAIL"

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"

export const ON_DUTY_TOGGLE_REQUEST = "ON_DUTY_TOGGLE_REQUEST"
export const ON_DUTY_TOGGLE_SUCCESS = "ON_DUTY_TOGGLE_SUCCESS"
export const ON_DUTY_TOGGLE_FAIL = "ON_DUTY_TOGGLE_FAIL"

export const UPDATE_FCM_REQUEST = "UPDATE_FCM_REQUEST"
export const UPDATE_FCM_SUCCESS = "UPDATE_FCM_SUCCESS"
export const UPDATE_FCM_FAIL = "UPDATE_FCM_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"